### ISSUE TITLE
No "Policy" spreadsheet format alternative

### ISSUE THREAD

**Issue by danieldafoe** [w3c/wcag-maturity-model#16]
In the Open Questions (1.4) section, there is mention of a third spreadsheet format for Policy, but there is no spreadsheet that exists for Policy since that is not one of the dimensions. Maybe I'm missing something, though.

I'm using the spreadsheet found at https://docs.google.com/spreadsheets/d/1fzPlHjHIaSQn9GvpJd86SDpV49U8Beg_iXj6K5aeyGg/edit#gid=1195503796 .

**Comment by jake-abma** [comment]
Thank you for bringing this issue to our attention.

I think you're right and it should be "Communications: (tab:  "[to be deleted, 20211013] Communications Evidence")

@Helixopp can you confirm? (Raph created it)

**Comment by Helixopp** [comment]
Yes, Jake is correct. To further clarify, we do not have multiple spreadsheets. What we intended to articulate was that the different tabs within the spreadsheet display different formats that we are considered. We do not have a separate Policy dimension, spreadsheet, or tab within the current spreadsheet. As Jake mentioned, the information that you are looking for can be found in the Communications tab. We realize we could have been more clear in the language.
