### ISSUE TITLE
Weird code thingy to b e deleted

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag-maturity-model#24]
Between sentences is a double space, I see a weird thingy in Github code (a red dot)... to be deleted

> Maturity Modeling is a big part of a “shift-left” methodology of preventing problems from recurring, not fixing them after they have happened.
>
> ​
> Most maturity models contain some number of levels with increasing levels of maturity.

**Comment by Helixopp** [comment]
deleted the red dot. You're right. This section needs to plain language editing. "shift-left" phrase is jargon. It needs to be replaced with a concise description of what we mean. This part needs more editing
