### ISSUE TITLE
Add "preventing barriers"

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag-maturity-model#26]
Change:

> The results of a maturity modeling assessment provide a holistic picture of an organization’s accessibility initiatives...where it is doing accessibility well, and where improvements can be made that remove barriers.

To:

> The results of a maturity modeling assessment provide a holistic picture of an organization’s accessibility initiatives...where it is doing accessibility well, and where improvements can be made removing and, even better, preventing barriers.

**Comment by Helixopp** [comment]
Great suggestions, Jake. I made the following plain language edits:

The results of a maturity modeling assessment provide a holistic picture of an organization’s accessibility initiatives, where accessibility is doing well, and where improvements, that remove and prevent barriers, can be made.
