### ISSUE TITLE
Variation Vs. Alternative

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag-maturity-model#30]
Flow change needed for:

We have proposed three variations on the spreadsheet formats.
Procurement is uses alternative 1
Knowledge & Skills is alternative 2
Policy is alternative 3

Change to:

We have proposed three variations on the spreadsheet format, the following dimensions all have their own format to be looked at:
1. Procurement
2. Knowledge & Skills
3. Policy

**Comment by jake-abma** [comment]
Also change "alternative" to "variation"

> Once we have feedback on which alternative is preferred, the other dimensions will migrate their spreadsheet format.

Once we have feedback on which variation is preferred, the other dimensions will migrate their spreadsheet format.

**Comment by Helixopp** [comment]
Great catch, and suggestion. I did some plain language editing to make sure what we mean is clearly understood by anyone. I edited the document to say the following: 

We have proposed three variations of spreadsheet formats, which can be found at the following spreadsheet tabs:
Procurement uses variation 1
Knowledge & Skills uses variation 2
Policy uses variation 3
