### ISSUE TITLE
Section 3.2 should be clarified.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/wcag-maturity-model#44]
The paragraph beginning "Measures:" isn't clear, and I don't understand it.

Section 3.2.1.1: the heading is about employing people with desired knowledge and skills, but the text appears to be about identifying what knowledge and skills are necessary, and the items in the list don't make sense.

Later subsections under "proof points" also have a lack of clarity - especially in the unordered lists, which are just brief phrases that often don't state clearly what is needed. I suggest rewriting them as phrases or, if necessary, full sentences that describe what each point means (appropriately for a reader who doesn't already know). Essentially, review for clarity and revise accordingly.

**Comment by jake-abma** [comment]
Thank you for bringing this issue to our attention. We will review and edit accordingly.

**Comment by Helixopp** [comment]
Maturity Model Subgroup member, Jeff Kline, will be reviewing, and addressing, this issue.

**Comment by Helixopp** [comment]
Our response: Introduction: Internal and external personnel at all levels of an organization must have W3C ICT accessibility knowledge and skills that are relevant to their organizational role. Accessibility knowledge and skills relevant to each individual’s position helps ensure that it is integrated and considered in all areas of an organization where ICT accessibility plays a role.
This could include but is not limited to: Developers, testers content producers, procurement, web managers, marketing and communications, HR, and other roles

Measures: education, individual experience, stakeholder responsibilities, departments, or units. Takes into account the use of external sources to bridge inclusiveness and accessibility gaps.
