### ISSUE TITLE
Is section 3.5 consistent with the employment laws applicable in different countries/regions?

### ISSUE THREAD

**Issue by jasonjgw** [w3c/wcag-maturity-model#47]
According to literature that I have read, some countries have laws which establish quotas of employees with disabilities that employers are expected to fill. In certain other countries, there are no quotas, but there are anti-discrimination laws in place which apply to all stages of the employment process.

Are the activities described in section 3.5 actually allowed under anti-discrimination laws related to employment practices? Are they consistent with different regimes of employment law around the world?

**Comment by Helixopp** [comment]
By design, this Maturity Model, and document, does not intend to adress employment law , regulations, or guidance. It is intended to guide entities in creating the infrastructure needed to improve accessibility over the long term.

**Comment by jasonjgw** [comment]
To clarify my point in raising the issue, it would be problematic for this document to recommend anything that might lead organizations to contravene local law (e.g., anti-discrimination provisions) without at least providing a warning in the text.
